### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by joaochris** [R030t1/VirtualMonitor#1]
Hi! Can you help me how do I install?

**Comment by R030t1** [comment]
Hi. I apologize for the lack of a README, the project is not complete. The current code is an attempt to adapt the Microsoft-provided display driver example to provide a virtual monitor.

If you need further information you should refer to the Windows driver examples; the example given will show a fake display in device manager. There is some plumbing still required to mirror your existing desktop.

I ran out of time/money to finish this. If you need something immediately there are existing commercial products.
